"""Everything the walk says that the model doesn't write, in each supported language.

Directions and the fixed phrases around them are filled in by code, so they are translated
here by hand rather than left to the model. To add a language, copy a block and translate it.
`dirs` runs clockwise from north; `turns` uses the routing server's names for each manoeuvre.
"""

LANGS = {
    "en": {
        "name": "English",
        "address": '',
        "piper": "en_US-lessac-medium",
        "dirs": ["north", "north-east", "east", "south-east", "south", "south-west", "west", "north-west"],
        "away": "{name} is about {dist} away, to the {dir}. That's roughly {min} on foot.",
        "minute": "1 minute", "minutes": "{n} minutes",
        "head": "head {dir} on {way}",
        "turns": {
            "left": "turn left onto {way}", "right": "turn right onto {way}",
            "slight left": "bear left onto {way}", "slight right": "bear right onto {way}",
            "sharp left": "turn sharply left onto {way}", "sharp right": "turn sharply right onto {way}",
        },
        "straight": "continue onto {way}", "uturn": "turn around",
        "for": "{action} for about {dist}", "then": ", then ",
        "more": " From there, keep heading towards {name}; the map on your phone has the rest.",
        "path": "the path",
        "m": "metres", "km": "kilometres", "ft": "feet", "mi": "miles", "dec": ".",
        "home": "your starting point", "area": "your neighbourhood",
        "title": "{area}: a {minutes}-minute walk",
        "welcome": "Welcome", "goodbye": "Welcome back",
        "first_here": " Your first stop is right where you're standing. Press play when you're ready.",
        "first_way": " Here's the way to your first stop. ",
        "press": " Press play when you get there.",
        "stop": "Stop {k}. {name}. ",
        "next_way": " When you're ready, here's the way to stop {k}. ",
        "back_here": " That brings you back to where you started. Press play for a short goodbye.",
        "back_way": " When you're ready, here's the way back. ",
        "back_press": " Press play when you're back for a short goodbye.",
    },
    "es": {
        "name": "Spanish",
        "address": ' Address the listener informally as "tú", never "usted" or "vosotros".',
        "piper": "es_ES-davefx-medium",
        "dirs": ["el norte", "el noreste", "el este", "el sureste", "el sur", "el suroeste", "el oeste",
                 "el noroeste"],
        "away": "{name} está a unos {dist}, hacia {dir}. Son aproximadamente {min} a pie.",
        "minute": "1 minuto", "minutes": "{n} minutos",
        "head": "dirígete hacia {dir} por {way}",
        "turns": {
            "left": "gira a la izquierda por {way}", "right": "gira a la derecha por {way}",
            "slight left": "desvíate ligeramente a la izquierda por {way}",
            "slight right": "desvíate ligeramente a la derecha por {way}",
            "sharp left": "haz un giro cerrado a la izquierda por {way}",
            "sharp right": "haz un giro cerrado a la derecha por {way}",
        },
        "straight": "continúa por {way}", "uturn": "da media vuelta",
        "for": "{action} durante unos {dist}", "then": ", luego ",
        "more": " Desde ahí, sigue en dirección a {name}; el mapa de tu teléfono tiene el resto.",
        "path": "el sendero",
        "m": "metros", "km": "kilómetros", "ft": "pies", "mi": "millas", "dec": ",",
        "home": "tu punto de partida", "area": "tu barrio",
        "title": "{area}: un paseo de {minutes} minutos",
        "welcome": "Bienvenida", "goodbye": "De vuelta",
        "first_here": " Tu primera parada está justo donde estás. Pulsa reproducir cuando quieras.",
        "first_way": " Este es el camino hacia tu primera parada. ",
        "press": " Pulsa reproducir cuando llegues.",
        "stop": "Parada {k}. {name}. ",
        "next_way": " Cuando quieras, este es el camino hacia la parada {k}. ",
        "back_here": " Con esto vuelves al punto de partida. Pulsa reproducir para una breve despedida.",
        "back_way": " Cuando quieras, este es el camino de vuelta. ",
        "back_press": " Pulsa reproducir cuando hayas vuelto para una breve despedida.",
    },
    "fr": {
        "name": "French",
        "address": ' Address the listener as "vous".',
        "piper": "fr_FR-siwis-medium",
        "dirs": ["le nord", "le nord-est", "l'est", "le sud-est", "le sud", "le sud-ouest", "l'ouest",
                 "le nord-ouest"],
        "away": "{name} se trouve à environ {dist}, vers {dir}. Cela fait à peu près {min} à pied.",
        "minute": "1 minute", "minutes": "{n} minutes",
        "head": "partez vers {dir} par {way}",
        "turns": {
            "left": "tournez à gauche sur {way}", "right": "tournez à droite sur {way}",
            "slight left": "prenez légèrement à gauche sur {way}",
            "slight right": "prenez légèrement à droite sur {way}",
            "sharp left": "tournez franchement à gauche sur {way}",
            "sharp right": "tournez franchement à droite sur {way}",
        },
        "straight": "continuez sur {way}", "uturn": "faites demi-tour",
        "for": "{action} pendant environ {dist}", "then": ", puis ",
        "more": " Ensuite, continuez en direction de {name} ; la carte sur votre téléphone indique la suite.",
        "path": "le chemin",
        "m": "mètres", "km": "kilomètres", "ft": "pieds", "mi": "miles", "dec": ",",
        "home": "votre point de départ", "area": "votre quartier",
        "title": "{area} : une balade de {minutes} minutes",
        "welcome": "Bienvenue", "goodbye": "De retour",
        "first_here": " Votre premier arrêt se trouve là où vous êtes. Appuyez sur lecture quand vous êtes prêt.",
        "first_way": " Voici le chemin vers votre premier arrêt. ",
        "press": " Appuyez sur lecture une fois sur place.",
        "stop": "Arrêt {k}. {name}. ",
        "next_way": " Quand vous serez prêt, voici le chemin vers l'arrêt {k}. ",
        "back_here": " Vous voilà revenu à votre point de départ. Appuyez sur lecture pour un court au revoir.",
        "back_way": " Quand vous serez prêt, voici le chemin du retour. ",
        "back_press": " Appuyez sur lecture à votre retour pour un court au revoir.",
    },
    "de": {
        "name": "German",
        "address": ' Address the listener formally as "Sie".',
        "piper": "de_DE-thorsten-medium",
        "dirs": ["Norden", "Nordosten", "Osten", "Südosten", "Süden", "Südwesten", "Westen", "Nordwesten"],
        "away": "{name} ist etwa {dist} entfernt, Richtung {dir}. Das sind ungefähr {min} zu Fuß.",
        "minute": "1 Minute", "minutes": "{n} Minuten",
        "head": "folgen Sie {way} Richtung {dir}",
        "turns": {
            "left": "biegen Sie links ab und folgen Sie {way}",
            "right": "biegen Sie rechts ab und folgen Sie {way}",
            "slight left": "halten Sie sich leicht links und folgen Sie {way}",
            "slight right": "halten Sie sich leicht rechts und folgen Sie {way}",
            "sharp left": "biegen Sie scharf links ab und folgen Sie {way}",
            "sharp right": "biegen Sie scharf rechts ab und folgen Sie {way}",
        },
        "straight": "folgen Sie weiter {way}", "uturn": "kehren Sie um",
        "for": "{action}, etwa {dist}", "then": ", dann ",
        "more": " Gehen Sie von dort weiter zum Ziel: {name}. Die Karte auf Ihrem Handy zeigt den Rest.",
        "path": "dem Weg",
        "m": "Meter", "km": "Kilometer", "ft": "Fuß", "mi": "Meilen", "dec": ",",
        "home": "Ihr Ausgangspunkt", "area": "Ihr Viertel",
        "title": "{area}: ein Spaziergang von {minutes} Minuten",
        "welcome": "Willkommen", "goodbye": "Zurück am Start",
        "first_here": " Ihr erster Halt ist genau dort, wo Sie stehen. Drücken Sie auf Wiedergabe, wenn Sie bereit sind.",
        "first_way": " Hier ist der Weg zu Ihrem ersten Halt. ",
        "press": " Drücken Sie auf Wiedergabe, wenn Sie dort sind.",
        "stop": "Halt {k}. {name}. ",
        "next_way": " Wenn Sie bereit sind, hier ist der Weg zu Halt {k}. ",
        "back_here": " Damit sind Sie wieder am Ausgangspunkt. Drücken Sie auf Wiedergabe für einen kurzen Abschied.",
        "back_way": " Wenn Sie bereit sind, hier ist der Rückweg. ",
        "back_press": " Drücken Sie auf Wiedergabe, wenn Sie zurück sind, für einen kurzen Abschied.",
    },
    "it": {
        "name": "Italian",
        "address": ' Address the listener informally as "tu".',
        "piper": "it_IT-paola-medium",
        "dirs": ["nord", "nord-est", "est", "sud-est", "sud", "sud-ovest", "ovest", "nord-ovest"],
        "away": "{name} si trova a circa {dist}, verso {dir}. Sono più o meno {min} a piedi.",
        "minute": "1 minuto", "minutes": "{n} minuti",
        "head": "dirigiti verso {dir} lungo {way}",
        "turns": {
            "left": "gira a sinistra e prosegui lungo {way}", "right": "gira a destra e prosegui lungo {way}",
            "slight left": "tieni leggermente la sinistra lungo {way}",
            "slight right": "tieni leggermente la destra lungo {way}",
            "sharp left": "gira nettamente a sinistra e prosegui lungo {way}",
            "sharp right": "gira nettamente a destra e prosegui lungo {way}",
        },
        "straight": "prosegui lungo {way}", "uturn": "torna indietro",
        "for": "{action} per circa {dist}", "then": ", poi ",
        "more": " Da lì, continua verso la destinazione: {name}. La mappa sul telefono ha il resto.",
        "path": "il sentiero",
        "m": "metri", "km": "chilometri", "ft": "piedi", "mi": "miglia", "dec": ",",
        "home": "il tuo punto di partenza", "area": "il tuo quartiere",
        "title": "{area}: una passeggiata di {minutes} minuti",
        "welcome": "Benvenuto", "goodbye": "Bentornato",
        "first_here": " La tua prima tappa è proprio dove ti trovi. Premi play quando vuoi.",
        "first_way": " Ecco la strada per la tua prima tappa. ",
        "press": " Premi play quando arrivi.",
        "stop": "Tappa {k}. {name}. ",
        "next_way": " Quando vuoi, ecco la strada per la tappa {k}. ",
        "back_here": " Così sei tornato al punto di partenza. Premi play per un breve saluto.",
        "back_way": " Quando vuoi, ecco la strada del ritorno. ",
        "back_press": " Premi play quando sei tornato per un breve saluto.",
    },
}
